name: Compilação do PDF

on:
  release:
    types: [created]

jobs:
  latex:
    runs-on: ubuntu-latest
    steps:
      - name: Baixando o código
        uses: actions/checkout@v4

      - name: Compilando latex
        uses: xu-cheng/latex-action@v3
        with:
          root_file: monografia.tex
          
      - name: Obtendo nome da TAG
        id: get_version
        # https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
        # run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT

      - name: Renomeando o PDF
        run: mv monografia.pdf monografia-${{ steps.get_version.outputs.VERSION }}.pdf

      - name: Publicando PDF
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: monografia-${{ steps.get_version.outputs.VERSION }}.pdf